name: Test and upload model on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test-model-pr:
    uses: ersilia-os/ersilia-model-workflows/.github/workflows/test-model-pr.yml@main
    with:
      branch: "main"
      repo_name: ${{ github.event.repository.name }}
