name: Call test model source

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-model-test:
    if: github.repository != 'ersilia-os/eos-template'
    uses: ersilia-os/ersilia-model-workflows/.github/workflows/test-model-source.yml@main
    with:
      branch: "main"
      repo_name: ${{ github.event.repository.name }}
    secrets:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}